# Numpy

## 1-it is a python library/package for mathematical computing and processing multi-dimensional array
## 2-it is written in c
## 3-it overcomes the problem of running slower algorithms on python by using multidimensional array
## 4-executes elementwise operation
## 5-performs linear alegbra ,fourier transform or any complex operation on it
## 6-core data structure of numpy is nd-array


### 1- normal python coding for dividing two parallel data

In [2]:
d=[400,300,100,200]
sp=[40,50,70,60]
m=list(zip(d,sp))
m

[(400, 40), (300, 50), (100, 70), (200, 60)]

In [6]:
main=[]
for i in m:
    l1=[]
    for j in i:
        l1.append(j)
    main.append(l1)
main
        
    

[[400, 40], [300, 50], [100, 70], [200, 60]]

In [9]:
time=[]
for k in main:
    time.append(k[0]/k[1])
print(time)
    

[10.0, 6.0, 1.4285714285714286, 3.3333333333333335]


### 2 - when we use numpy

In [10]:
import numpy as np
d1=np.array([400,300,100,200])
sp1=np.array([40,50,70,60])
d1/sp1

array([10.        ,  6.        ,  1.42857143,  3.33333333])

## Array

## 1 = stores homogenous data
## 2 = only in numbers
## 3 = fast and efficient
## 4 = operates only on homogenous data (only numbers)

# Creating array

In [14]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
type(a)

numpy.ndarray

In [16]:
a.dtype

dtype('int32')

In [17]:
# 2d array creation
a2 = np.array([[1,3,7,9],[45,89,56,11]])
a2

array([[ 1,  3,  7,  9],
       [45, 89, 56, 11]])

In [22]:
# 3d array creation
s = np.array([[[1,2,3,4],[2,4,6,8]],[[20,45,56,90],[45,78,90,45]]])
s

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8]],

       [[20, 45, 56, 90],
        [45, 78, 90, 45]]])

In [19]:
# creating array from tuple
s = np.array((1,3,5,7,9))
s

array([1, 3, 5, 7, 9])

In [20]:
# creating array from string
s = np.array("hi hello why")
s
#it is a 0th.darray

array('hi hello why', dtype='<U12')

# Important properties \ attributes of Array:
## 1. ndim
## 2. shape
## 3. size
## 4. astype

In [23]:
# single dimensional array 
a = np.array([20,30,90])
print(a)

[20 30 90]


## property 1 of array - ndim

In [24]:
a.ndim

1

In [27]:
# 2d array
c = np.array([[1,2,3],[23,45,60]])
print(c)
print("")
print(c.ndim)

[[ 1  2  3]
 [23 45 60]]

2


In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5]) # in  single dimension we can not judge the rows and columns
c = np.array([[1, 2, 3,45], [4, 5, 6,7],[3,5,6,7]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e=np.array([[[[1, 2, 3], [4, 5, 6]]]])
f=np.array([[2,3,4,5]])
g=np.array([[[[[20,30]]]]])
print(a.ndim)
print(np.ndim(a))
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)
print(g.ndim)


0
0
1
2
3
4
2
5


In [29]:
a1=np.array([1,2,3,4],ndmin=5)
a1

array([[[[[1, 2, 3, 4]]]]])

In [30]:
c = np.array([[1,2,3],[23,45,60]],ndmin=7)
c

array([[[[[[[ 1,  2,  3],
            [23, 45, 60]]]]]]])

## property of array 2 - shape

In [32]:
a1=np.array([1,2,3,4]) ## in 1d shape we cannot judge rows and columns
print(a1.shape)

(4,)


In [33]:
# determining of shape in 2d array
c = np.array([[1, 2, 3], [4, 5, 6]])
c.shape

(2, 3)

In [34]:
c = np.array([[1, 2, 3,45], [4, 5, 6,7],[3,5,6,7]])
c.shape

(3, 4)

In [35]:
c = np.array([[1, 2, 3]])
c.shape

(1, 3)

In [36]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.shape

(2, 2, 3)

In [38]:
k=np.array([[[[[[[2,3,4],[45,78,90],[50,90,89]]]]]]])
print(k.shape)
print(k)


(1, 1, 1, 1, 1, 3, 3)
[[[[[[[ 2  3  4]
      [45 78 90]
      [50 90 89]]]]]]]


In [39]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a.shape


(1, 1, 1, 1, 1, 1, 1, 4)

In [2]:
import numpy as np
k = np.array([[[2,3],[2,3],[2,3],[2,3]],[[2,3],[2,3],[2,3],[2,3]]])
k.shape

(2, 4, 2)

In [8]:
#create a shape odf array 1,1,3,3
j = np.array([[[[2,3,4],[3,5,6],[6,7,8]]]])
print(j)
print(j.shape)

[[[[2 3 4]
   [3 5 6]
   [6 7 8]]]]
(1, 1, 3, 3)


In [11]:
#1,1,3,3,3
k = np.array([[[[[2,3,4],[2,3,4],[2,3,4]],[[2,3,4],[2,3,4],[2,3,4]],[[2,3,4],[2,3,4],[2,3,4]]]]])
k.shape

5

## rank is the same as number of dimension

In [14]:
d = np.array([20,40,70,90])
print(np.size(d))
print(np.size(d,axis=0))

4
4


In [18]:
a = np.array([[1,2,3,4],[4,5,6,7]])
print(np.size(a))
print(np.size(a,0))
print(np.size(a,1))

8
2
4


In [24]:
# 3d Array
a = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[2,5,3,4]]])
print(np.size(a))
print(np.size(a,0))
print(np.size(a,1))
print(np.size(a,2))


16
2
2
4


## item size it specifies how much memory does one element is alloted - always shows in bits 

In [26]:
# item size it always shows in bits
print(a.size*a.itemsize)

64


### dtype always in default is float


In [28]:
a=np.ones((2,3))
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [31]:
# create an array of shape 2,3,1
a=np.ones((2,3,1))
a

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

## astype - conversion of one datatype to another

In [35]:
a1=a.astype("int")
print(a1)
print(a1.dtype)

[[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]
int32


## arrays are faster then list datatype (coding is short in arrays)
## arrays can perform element wise operation while list cannot
## arrays take less memory

In [36]:

import sys
l=list(range(100))
a=np.arange(100)
print(sys.getsizeof(l))
print(a.itemsize)
print("list takes :",sys.getsizeof(l)*len(l),"bytes")  ##ys.getsizeof(l) : size of each element in the list
print("array takes : ",a.itemsize*a.size,"bytes" ) ## itemsize: size of each element in the array.


856
4
list takes : 85600 bytes
array takes :  400 bytes


# Array Indexing : in 1D

In [39]:
a = np.array([1,2,3,4])
print(a[0])
print(a[2:])
print(a[1:5:3])

1
[3 4]
[2]


## Array Indexing : In 2D

In [53]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
print(a[0])

print(a[-1])

print(a[-1][2])

print(a[-1][3:])

print(a[:,1])

print(a[:,1:5:3])

print(a[0:3:2,0:4:3])
print(a)

[2 3 4 5 6]
[20 30 40 50 90]
40
[50 90]
[ 3  8 30]
[[ 3  6]
 [ 8 90]
 [30 90]]
[[ 2  5]
 [20 50]]
[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]


In [52]:
print(a[0:3:2])

[[ 2  3  4  5  6]
 [20 30 40 50 90]]


In [56]:
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 90],
       [20, 30, 40, 50, 90]])

In [55]:
a[1:3,1:3]

array([[ 8,  9],
       [30, 40]])

In [57]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])  # 2d array  here , 
print(a)
print(a[0]) #or print(a[-3]) means first row
print(a[1]) #or print(a[-2]) means second row
print(a[2]) #or print(a[-1]) means third row
print(a[-1]) # or print(a[2])  means  last row
print(a[0][2]) # fetch 4
print(a[1][2:]) # 9,0,90
print(a[-2][0])  # fetch 7
print(a[:,2])  ## all rows with 2nd column  (discontinous manner)
print(a[0:2,2:]) ## ist and 2nd rows with columns from 2nd(disconinous manner)
print(a[1,2:3])
print(a[0:3:2,2:5:2]) ## feth 4,6 40 ,90
#print(a[[0,2],[1,3]])
print(a[0:3:2,1:4:2]) ## fetch 3, 30 5 and 50
 


[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]
[2 3 4 5 6]
[ 7  8  9  0 90]
[20 30 40 50 90]
[20 30 40 50 90]
4
[ 9  0 90]
7
[ 4  9 40]
[[ 4  5  6]
 [ 9  0 90]]
[9]
[[ 4  6]
 [40 90]]
[[ 3  5]
 [30 50]]


In [66]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a


array([[[[[[[['pizza', 'sweet corn', 'coffee', 'lemonade']]]]]]]],
      dtype='<U10')

In [60]:
print(a[0][0][0][0][0][0][0])

['pizza' 'sweet corn' 'coffee' 'lemonade']


In [69]:
print(a[0][0][0][0][0][0][0][1:])

['sweet corn' 'coffee' 'lemonade']


In [70]:
a=np.array([[[[[1,2,3,50,],[4,5,6,90],[7,8,9,99],[11,12,3,98]]]]])
a

array([[[[[ 1,  2,  3, 50],
          [ 4,  5,  6, 90],
          [ 7,  8,  9, 99],
          [11, 12,  3, 98]]]]])

In [71]:
a[0][0][0][-1][-1]

98

In [72]:
a[0][0][0][3][-1]


98

In [73]:
a=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
a

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9,  0],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [74]:
a[0][0][-1][-2]

19

In [76]:
a[0][0][2][2:5:2]

array([13, 15])

In [2]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
arr[1][0]

array([7, 8, 9])

In [10]:
arr[1][:,1:] # 8,9,11,12 or # 11,12

array([[ 8,  9],
       [11, 12]])

## Indexing With Boolean (Important From EDA Point OF View

In [11]:
a=np.array([[20,30,60],[40,80,90],[70,90,100]])
a


array([[ 20,  30,  60],
       [ 40,  80,  90],
       [ 70,  90, 100]])

In [12]:
a<40

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [14]:
z=a<40
z

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [16]:
print(a[z])
# or 
print(a[a<40])

[20 30]
[20 30]


In [17]:
## np.where returns index
[np.where(a<40,85,"Nothing")]

[array([['85', '85', 'Nothing'],
        ['Nothing', 'Nothing', 'Nothing'],
        ['Nothing', 'Nothing', 'Nothing']], dtype='<U11')]

In [22]:
## greater than 40 and also even
print(a[(a%2==0)&(a>40)])


[ 60  80  90  70  90 100]


In [23]:
a=[[[[2,3,4,5],[40,50,60,90]]]]
a

[[[[2, 3, 4, 5], [40, 50, 60, 90]]]]

In [65]:
m=np.array(a)
m
print(m[0][0][:,1])
print(m[0][0][1,2:])
print(m[0][0][[0,1],[1,3]])


[ 3 50]
[60 90]
[ 3 90]


In [90]:
m[0][0][:,2]

array([ 4, 60])

# How TO fetch Each Element Of Array Using Loop In Order to perform Any # 
# Logic On Each Element : Using np.nditer


In [94]:
a = np.array([[2,3,4],[5,6,7]])
print(a)
for i in np.nditer(a):
    print(i)

[[2 3 4]
 [5 6 7]]
2
3
4
5
6
7


## Copy and View

In [95]:
##   copy
a = np.array([1,2,3,4])
a1=a.copy() # Deep Copy
a1[3]=70
print("copy...",a1)
print("Original Array..",a)

copy... [ 1  2  3 70]
Original Array.. [1 2 3 4]


In [96]:
#  VIew
a = np.array([1,2,3,4])
a1=a.view() # Deep Copy
a1[3]=70
print("copy...",a1)
print("Original Array..",a)

copy... [ 1  2  3 70]
Original Array.. [ 1  2  3 70]


In [97]:
## Another Example Of View Copy
a2=a1 #
a2[2]=200
print("original..",a1)
print("View Copy..",a2)


original.. [  1   2 200  70]
View Copy.. [  1   2 200  70]


## Shape Manipulation : Reshape , Resize (Shallow=Reshape,DeepCopy=Resize

In [98]:
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x.shape

(2, 6)

In [105]:

# RESHAPE

x1=x.reshape(1,12)
print("deep copy..",x1)
print("original array..",x)
x2=x.reshape(3,4)
print("Copy 2..",x2)
x3=x.reshape(6,2)
print("Copy 3..",x3)


deep copy.. [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
original array.. [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Copy 2.. [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Copy 3.. [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [106]:
#       Resize
x1=x.resize(1,12)
print("deep copy..",x1) ## Return None ... Changes Original Data
print("original array..",x)


deep copy.. None
original array.. [[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [109]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr= arr.reshape(2,2,-1)
newarr1= arr.reshape(-1,2,2)
print(newarr)
print(newarr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#  Flatten The Array - Ravel (Shallow Copy),Flatten(Deepcopy)
### Flattening The Arrays means Converting Multi-dimensional Arrays Into 1D Arrays..

In [111]:
# By USing Reshape

arr = np.array([[1,2,3],[4,5,7]])
arr1 = arr.ravel()
print("!d ..",arr1)
print("2d ..",arr)

!d .. [1 2 3 4 5 7]
2d .. [[1 2 3]
 [4 5 7]]


In [112]:
arr1[2]=360
print(arr,"Original")
print(arr1,"Deep Copy")

[[  1   2 360]
 [  4   5   7]] Original
[  1   2 360   4   5   7] Deep Copy


In [116]:
# By Using Flatten

arr = np.array([[1,2,3],[4,5,7]])
arr1 = arr.flatten()
print("1d ..",arr1,"Copy")
print("2d ..",arr,"original")
arr1[2]=360
print(arr,"Original")
print(arr1,"shallow Copy")

1d .. [1 2 3 4 5 7] Copy
2d .. [[1 2 3]
 [4 5 7]] original
[[1 2 3]
 [4 5 7]] Original
[  1   2 360   4   5   7] shallow Copy


In [115]:
# BY Using Reshape -1

arr = np.array([[1,2,3],[4,5,7]])
arr1 = arr.reshape(-1)
print("1d ..",arr1,"Copy")
print("2d ..",arr,"original")
arr1[2]=360
print(arr,"Original")
print(arr1,"Deep Copy")

1d .. [1 2 3 4 5 7] Copy
2d .. [[1 2 3]
 [4 5 7]] original


# Arange - Returns an Arrays Of Consecutive Generated Numbers



In [119]:
a=np.arange(1,11)
print(a)
a1=np.arange(1,11,2)
print(a1)
a2=np.arange(1.1,11.2,0.2)
print(a2)


[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1.1  1.3  1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.5  3.7
  3.9  4.1  4.3  4.5  4.7  4.9  5.1  5.3  5.5  5.7  5.9  6.1  6.3  6.5
  6.7  6.9  7.1  7.3  7.5  7.7  7.9  8.1  8.3  8.5  8.7  8.9  9.1  9.3
  9.5  9.7  9.9 10.1 10.3 10.5 10.7 10.9 11.1]


## Line Space 

In [121]:
a=np.linspace(-30,30,10) # 10 elemnts Generated # linspace() creates an array of equally spaced 10 elements
a

array([-30.        , -23.33333333, -16.66666667, -10.        ,
        -3.33333333,   3.33333333,  10.        ,  16.66666667,
        23.33333333,  30.        ])

In [122]:
a=np.arange(-30,30,10) # 10 elemnts not Generated
a

array([-30, -20, -10,   0,  10,  20])

# LogSpace : Generates Log Value Of Linspace

In [124]:
a=np.logspace(-30,30,10) # Show Log Value of Linspace
a

array([1.00000000e-30, 4.64158883e-24, 2.15443469e-17, 1.00000000e-10,
       4.64158883e-04, 2.15443469e+03, 1.00000000e+10, 4.64158883e+16,
       2.15443469e+23, 1.00000000e+30])

In [1]:
a=[[[[2,3,4,5],[40,50,60,90]]]]
a

[[[[2, 3, 4, 5], [40, 50, 60, 90]]]]

In [3]:
import numpy as np
a=np.array([[[[2,3,4,5],[40,50,60,90]]]])
a

array([[[[ 2,  3,  4,  5],
         [40, 50, 60, 90]]]])

In [8]:
print(a[0][0][[0,1],[1,3]])

[ 3 90]


In [19]:
a=np.arange(3,30,2) #,,13 15 21 29
print(a)
print(a[[5,6,9,13]])

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[13 15 21 29]


# some arrays are used for initialization purpose
# 1 np.ones()
# 2 np.zeros()
# 3 np.empty()

In [20]:
a = np.empty([2,4])
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 8.57697961e-321 1.78019082e-306 1.37959740e-306]]


In [24]:
a = np.empty([1,3],dtype="int")
a

array([[551493552,       563,         0]])

In [23]:
a.dtype

dtype('int32')

In [27]:
a=np.zeros([3,4],dtype="int")
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
a=np.ones([1,5])
a

array([[1., 1., 1., 1., 1.]])

In [37]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,3]])
a1

a2=np.array([[3,20,5,4],[3,4,50,6],[7,8,7,9]])
a2


array([[ 3, 20,  5,  4],
       [ 3,  4, 50,  6],
       [ 7,  8,  7,  9]])

In [38]:
a1+a2

array([[ 4, 22,  8,  8],
       [ 6,  8, 55, 12],
       [14, 16, 16, 12]])

In [39]:
a1*a2

array([[  3,  40,  15,  16],
       [  9,  16, 250,  36],
       [ 49,  64,  63,  27]])

In [40]:
a1/a2

array([[0.33333333, 0.1       , 0.6       , 1.        ],
       [1.        , 1.        , 0.1       , 1.        ],
       [1.        , 1.        , 1.28571429, 0.33333333]])

In [41]:
a1<a2

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [44]:
[a1<a2]

TypeError: 'numpy.ndarray' object is not callable

In [45]:
a1>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
a1 = [[4,9,16,36]]
a1

[[4, 9, 16, 36]]

In [47]:
np.sqrt(a1)

array([[2., 3., 4., 6.]])

In [48]:
np.sin(a1)

array([[-0.7568025 ,  0.41211849, -0.28790332, -0.99177885]])

In [49]:
import math
a = 2.3
math.floor(a)

2

In [51]:
a = -3.4
math.ceil(a)

-3

In [57]:
round(23.56789)

24

In [58]:
np.ceil(a1)

array([[ 4.,  9., 16., 36.]])

In [59]:
np.floor(a1)

array([[ 4.,  9., 16., 36.]])

In [60]:
a1= np.array([20.4,-2.6,3.9])
np.ceil(a1)

array([21., -2.,  4.])

In [61]:
np.floor(a1)

array([20., -3.,  3.])

In [62]:
np.min(a1)

-2.6

In [63]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,0]])
a1


array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [64]:
np.argmax(a1)

10

In [65]:
np.max(a1)

9

In [66]:
a1.max(axis=0)

array([7, 8, 9, 6])

In [67]:
a1.max(axis=1)

array([4, 6, 9])

In [68]:
a1.sum(axis=0)

array([11, 14, 17, 10])

In [69]:
a1.sum(axis=1)

array([10, 18, 24])

In [73]:
np.sort(a1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 7, 8, 9]])

In [74]:
np.sort(a1,axis=0)

array([[0, 2, 3, 4],
       [1, 4, 5, 6],
       [3, 7, 8, 9]])

In [75]:
np.sort(a1,axis=1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 7, 8, 9]])

## difference between Matrix and Array
###  - matrix atmost is 2(dimensional) and Arrays Are N(dimensional)

In [76]:
a=np.mat([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [78]:
a= np.mat([[1,2,3],[4,5,6],[7,8,9]])
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
a= np.mat([[[1,2,3],[4,5,6],[7,8,9]]])
a  ## ValueError("matrix must be 2-dimensional")

ValueError: matrix must be 2-dimensional

In [81]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[3,4],[8,9]])
m1*m2 


array([[ 3,  8],
       [24, 36]])

In [82]:
m1=np.mat([[1,2],[3,4]])
m2=np.mat([[3,4],[8,9]])
m1*m2 


matrix([[19, 22],
        [41, 48]])

In [83]:
m1=np.array([[1,2],[3,4]])
m1.T

array([[1, 3],
       [2, 4]])

In [86]:
m1=np.mat([[1,2],[3,4]])  ## Transpose- two ways of transposing by using .T or np.transpose
m1.T

matrix([[1, 3],
        [2, 4]])

In [87]:
m1=np.array([[1,2],[3,4]])
np.transpose(m1)

array([[1, 3],
       [2, 4]])

## Trace 

In [88]:
np.trace(m1)

5

## inverse

In [89]:
a=np.array([[1,2],[3,4]])  
d=np.matrix([[1,2],[3,4]])
print(a.shape)
print(d.shape)
np.linalg.inv(d)


(2, 2)
(2, 2)


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## Broadcasting

In [92]:
# case 1 When Shape Is Same
a = np.arange(8).reshape(2,4)
a1 = np.arange(8).reshape(2,4)
a+a1


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [94]:
# Case 2 When Shape Is Different 
a1=np.arange(9).reshape(3,3)
a1*4 ## Effect of Broadcast

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32]])

In [105]:
# Case 2.2 When shape is different
## Conditions Must Be met For  Broadcasting Which Is - One Of The Dimension Is Of Size 1 or It Will raise Error
a2= np.arange(12).reshape(4,3)
print(a2)
print(a1)
a1+a2

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


ValueError: operands could not be broadcast together with shapes (3,3) (4,3) 